In [14]:
import sys
!{sys.executable} -m pip install sportsipy

Collecting sportsipy
  Downloading sportsipy-0.6.0-py3-none-any.whl (499 kB)
     |████████████████████████████████| 499 kB 4.8 MB/s eta 0:00:01
Requirement already satisfied: pyquery>=1.4.0 in /opt/anaconda3/lib/python3.8/site-packages (from sportsipy) (1.4.3)
Requirement already satisfied: requests>=2.18.4 in /opt/anaconda3/lib/python3.8/site-packages (from sportsipy) (2.24.0)
Requirement already satisfied: pandas>=0.24.1 in /opt/anaconda3/lib/python3.8/site-packages (from sportsipy) (1.1.3)
Requirement already satisfied: cssselect>0.7.9 in /opt/anaconda3/lib/python3.8/site-packages (from pyquery>=1.4.0->sportsipy) (1.1.0)
Requirement already satisfied: lxml>=2.1 in /opt/anaconda3/lib/python3.8/site-packages (from pyquery>=1.4.0->sportsipy) (4.6.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.18.4->sportsipy) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.18.4->sportsipy) (2020.6.20)
Requirement already satisfied: idna<3,>=2.5 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.18.4->sportsipy) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/anaconda3/lib/python3.8/site-packages (from requests>=2.18.4->sportsipy) (3.0.4)
Requirement already satisfied: numpy>=1.15.4 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.1->sportsipy) (1.19.2)
Requirement already satisfied: pytz>=2017.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.1->sportsipy) (2020.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/anaconda3/lib/python3.8/site-packages (from pandas>=0.24.1->sportsipy) (2.8.1)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=0.24.1->sportsipy) (1.15.0)
Installing collected packages: sportsipy
Successfully installed sportsipy-0.6.0

In [131]:
from sportsipy.nfl.boxscore import Boxscores, Boxscore
Boxscores(1,2020).games
import pandas as pd
import numpy as np


from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.model_selection import train_test_split
# sklearn utilities
from sklearn import datasets
from sklearn.metrics import confusion_matrix, classification_report
from sklearn import preprocessing

# sklearn models
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [41]:
game_str = Boxscores(1,2019).games['1-2019'][3]['boxscore']
game_stats = Boxscore(game_str)
game_stats.dataframe
Boxscore(Boxscores(1,2019).games['1-2019'][3]['boxscore']).dataframe

,attendance,away_first_downs,away_fourth_down_attempts,away_fourth_down_conversions,away_fumbles,away_fumbles_lost,away_interceptions,away_net_pass_yards,away_pass_attempts,away_pass_completions,...,roof,stadium,surface,time,vegas_line,weather,winner,winning_abbr,winning_name,won_toss
201909080phi,69696,15,2,2,0,0,0,370,44,30,...,Outdoors,Lincoln Financial Field,Grass,1:00pm,Philadelphia Eagles -10.5,"79 degrees, relative humidity 49%, wind 4 mph",Home,PHI,Philadelphia Eagles,Eagles (deferred)

In [17]:
game_stats.dataframe.columns

Index(['attendance', 'away_first_downs', 'away_fourth_down_attempts',
       'away_fourth_down_conversions', 'away_fumbles', 'away_fumbles_lost',
       'away_interceptions', 'away_net_pass_yards', 'away_pass_attempts',
       'away_pass_completions', 'away_pass_touchdowns', 'away_pass_yards',
       'away_penalties', 'away_points', 'away_rush_attempts',
       'away_rush_touchdowns', 'away_rush_yards', 'away_third_down_attempts',
       'away_third_down_conversions', 'away_time_of_possession',
       'away_times_sacked', 'away_total_yards', 'away_turnovers',
       'away_yards_from_penalties', 'away_yards_lost_from_sacks', 'date',
       'datetime', 'duration', 'home_first_downs', 'home_fourth_down_attempts',
       'home_fourth_down_conversions', 'home_fumbles', 'home_fumbles_lost',
       'home_interceptions', 'home_net_pass_yards', 'home_pass_attempts',
       'home_pass_completions', 'home_pass_touchdowns', 'home_pass_yards',
       'home_penalties', 'home_points', 'home_rush_attempts',
       'home_rush_touchdowns', 'home_rush_yards', 'home_third_down_attempts',
       'home_third_down_conversions', 'home_time_of_possession',
       'home_times_sacked', 'home_total_yards', 'home_turnovers',
       'home_yards_from_penalties', 'home_yards_lost_from_sacks',
       'losing_abbr', 'losing_name', 'over_under', 'roof', 'stadium',
       'surface', 'time', 'vegas_line', 'weather', 'winner', 'winning_abbr',
       'winning_name', 'won_toss'],
      dtype='object')

In [61]:
def game_data(game_df,game_stats):
    try:
        away_team_df = game_df[['away_name', 'away_abbr', 'away_score']].rename(columns = {'away_name': 'team_name', 'away_abbr': 'team_abbr', 'away_score': 'score'})
        home_team_df = game_df[['home_name','home_abbr', 'home_score']].rename(columns = {'home_name': 'team_name', 'home_abbr': 'team_abbr', 'home_score': 'score'})
        try:
            if game_df.loc[0,'away_score'] > game_df.loc[0,'home_score']:
                away_team_df = pd.merge(away_team_df, pd.DataFrame({'game_won' : [1], 'game_lost' : [0]}),left_index = True, right_index = True)
                home_team_df = pd.merge(home_team_df, pd.DataFrame({'game_won' : [0], 'game_lost' : [1]}),left_index = True, right_index = True)
            elif game_df.loc[0,'away_score'] < game_df.loc[0,'home_score']:
                away_team_df = pd.merge(away_team_df, pd.DataFrame({'game_won' : [0], 'game_lost' : [1]}),left_index = True, right_index = True)
                home_team_df = pd.merge(home_team_df, pd.DataFrame({'game_won' : [1], 'game_lost' : [0]}),left_index = True, right_index = True)
            else: 
                away_team_df = pd.merge(away_team_df, pd.DataFrame({'game_won' : [0], 'game_lost' : [0]}),left_index = True, right_index = True)
                home_team_df = pd.merge(home_team_df, pd.DataFrame({'game_won' : [0], 'game_lost' : [0]}),left_index = True, right_index = True)
        except TypeError:
                away_team_df = pd.merge(away_team_df, pd.DataFrame({'game_won' : [np.nan], 'game_lost' : [np.nan]}),left_index = True, right_index = True)
                home_team_df = pd.merge(home_team_df, pd.DataFrame({'game_won' : [np.nan], 'game_lost' : [np.nan]}),left_index = True, right_index = True)        

        away_stats_df = game_stats.dataframe[['away_first_downs', 'away_fourth_down_attempts',
               'away_fourth_down_conversions', 'away_fumbles', 'away_fumbles_lost',
               'away_interceptions', 'away_net_pass_yards', 'away_pass_attempts',
               'away_pass_completions', 'away_pass_touchdowns', 'away_pass_yards',
               'away_penalties', 'away_points', 'away_rush_attempts',
               'away_rush_touchdowns', 'away_rush_yards', 'away_third_down_attempts',
               'away_third_down_conversions', 'away_time_of_possession',
               'away_times_sacked', 'away_total_yards', 'away_turnovers',
               'away_yards_from_penalties', 'away_yards_lost_from_sacks']].reset_index().drop(columns ='index').rename(columns = {
               'away_first_downs': 'first_downs', 'away_fourth_down_attempts':'fourth_down_attempts',
               'away_fourth_down_conversions':'fourth_down_conversions' , 'away_fumbles': 'fumbles', 'away_fumbles_lost': 'fumbles_lost',
               'away_interceptions': 'interceptions', 'away_net_pass_yards':'net_pass_yards' , 'away_pass_attempts': 'pass_attempts',
               'away_pass_completions':'pass_completions' , 'away_pass_touchdowns': 'pass_touchdowns', 'away_pass_yards': 'pass_yards',
               'away_penalties': 'penalties', 'away_points': 'points', 'away_rush_attempts': 'rush_attempts',
               'away_rush_touchdowns': 'rush_touchdowns', 'away_rush_yards': 'rush_yards', 'away_third_down_attempts': 'third_down_attempts',
               'away_third_down_conversions': 'third_down_conversions', 'away_time_of_possession': 'time_of_possession',
               'away_times_sacked': 'times_sacked', 'away_total_yards': 'total_yards', 'away_turnovers': 'turnovers',
               'away_yards_from_penalties':'yards_from_penalties', 'away_yards_lost_from_sacks': 'yards_lost_from_sacks'})

        home_stats_df = game_stats.dataframe[['home_first_downs', 'home_fourth_down_attempts',
               'home_fourth_down_conversions', 'home_fumbles', 'home_fumbles_lost',
               'home_interceptions', 'home_net_pass_yards', 'home_pass_attempts',
               'home_pass_completions', 'home_pass_touchdowns', 'home_pass_yards',
               'home_penalties', 'home_points', 'home_rush_attempts',
               'home_rush_touchdowns', 'home_rush_yards', 'home_third_down_attempts',
               'home_third_down_conversions', 'home_time_of_possession',
               'home_times_sacked', 'home_total_yards', 'home_turnovers',
               'home_yards_from_penalties', 'home_yards_lost_from_sacks']].reset_index().drop(columns = 'index').rename(columns = {
               'home_first_downs': 'first_downs', 'home_fourth_down_attempts':'fourth_down_attempts',
               'home_fourth_down_conversions':'fourth_down_conversions' , 'home_fumbles': 'fumbles', 'home_fumbles_lost': 'fumbles_lost',
               'home_interceptions': 'interceptions', 'home_net_pass_yards':'net_pass_yards' , 'home_pass_attempts': 'pass_attempts',
               'home_pass_completions':'pass_completions' , 'home_pass_touchdowns': 'pass_touchdowns', 'home_pass_yards': 'pass_yards',
               'home_penalties': 'penalties', 'home_points': 'points', 'home_rush_attempts': 'rush_attempts',
               'home_rush_touchdowns': 'rush_touchdowns', 'home_rush_yards': 'rush_yards', 'home_third_down_attempts': 'third_down_attempts',
               'home_third_down_conversions': 'third_down_conversions', 'home_time_of_possession': 'time_of_possession',
               'home_times_sacked': 'times_sacked', 'home_total_yards': 'total_yards', 'home_turnovers': 'turnovers',
               'home_yards_from_penalties':'yards_from_penalties', 'home_yards_lost_from_sacks': 'yards_lost_from_sacks'})

        away_team_df = pd.merge(away_team_df, away_stats_df,left_index = True, right_index = True)
        home_team_df = pd.merge(home_team_df, home_stats_df,left_index = True, right_index = True)
        try:
            away_team_df['time_of_possession'] = (int(away_team_df['time_of_possession'].loc[0][0:2]) * 60) + int(away_team_df['time_of_possession'].loc[0][3:5])
            home_team_df['time_of_possession'] = (int(home_team_df['time_of_possession'].loc[0][0:2]) * 60) + int(home_team_df['time_of_possession'].loc[0][3:5])
        except TypeError:
            away_team_df['time_of_possession'] = np.nan
            home_team_df['time_of_possession'] = np.nan
    except TypeError:
        away_team_df = pd.DataFrame()
        home_team_df = pd.DataFrame()
    return away_team_df, home_team_df

In [62]:
def game_data_up_to_week(weeks,year):
    weeks_games_df = pd.DataFrame()
    for w in range(len(weeks)):
        date_string = str(weeks[w]) + '-' + str(year)
        week_scores = Boxscores(weeks[w],year)
        week_games_df = pd.DataFrame()
        for g in range(len(week_scores.games[date_string])):
            game_str = week_scores.games[date_string][g]['boxscore']
            game_stats = Boxscore(game_str)
            game_df = pd.DataFrame(week_scores.games[date_string][g], index = [0])
            away_team_df, home_team_df = game_data(game_df,game_stats)
            away_team_df['week'] = weeks[w]
            home_team_df['week'] = weeks[w]
            week_games_df = pd.concat([week_games_df,away_team_df])
            week_games_df = pd.concat([week_games_df,home_team_df])
        weeks_games_df = pd.concat([weeks_games_df,week_games_df])
    return weeks_games_df

In [83]:
saved_df = game_data_up_to_week(range(1,5),2018)

In [94]:
bigger_saved_df = game_data_up_to_week(range(5,10),2018)

In [129]:
saved_df = pd.concat([saved_df,bigger_saved_df])
saved_df.columns
saved_df

,team_name,team_abbr,score,game_won,game_lost,first_downs,fourth_down_attempts,fourth_down_conversions,fumbles,fumbles_lost,...,rush_yards,third_down_attempts,third_down_conversions,time_of_possession,times_sacked,total_yards,turnovers,yards_from_penalties,yards_lost_from_sacks,week
0,Atlanta Falcons,atl,12,0,1,16,1,0,1,0,...,74,15,4,1670,4,299,1,135,26,1
0,Philadelphia Eagles,phi,18,1,0,18,0,0,2,1,...,113,16,8,1930,2,232,2,101,13,1
0,Pittsburgh Steelers,pit,21,0,0,25,0,0,3,3,...,159,15,7,2112,4,472,6,116,22,1
0,Cleveland Browns,cle,21,0,0,22,1,0,1,0,...,177,18,5,2088,7,327,1,87,47,1
0,Buffalo Bills,buf,3,0,1,10,1,0,1,0,...,83,15,2,1486,6,153,2,100,28,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,New Orleans Saints,nor,45,1,0,31,2,2,1,1,...,141,12,7,2021,0,487,1,20,0,9
0,Green Bay Packers,gnb,17,0,1,22,1,0,2,1,...,117,13,6,1954,1,367,1,63,9,9
0,New England Patriots,nwe,31,1,0,28,1,0,0,0,...,123,11,4,1646,2,433,0,30,21,9
0,Tennessee Titans,oti,28,1,0,24,0,0,2,2,...,125,14,11,2066,4,340,2,20,25,9
0,Dallas Cowboys,dal,14,0,1,18,1,0,1,1,...,72,11,5,1534,5,297,2,52,18,9

In [128]:

y=saved_df["game_won"]
x=saved_df[list(saved_df.columns)[5:len(saved_df)]]

,first_downs,fourth_down_attempts,fourth_down_conversions,fumbles,fumbles_lost,interceptions,net_pass_yards,pass_attempts,pass_completions,pass_touchdowns,...,rush_yards,third_down_attempts,third_down_conversions,time_of_possession,times_sacked,total_yards,turnovers,yards_from_penalties,yards_lost_from_sacks,week
0,16,1,0,1,0,1,225,43,21,0,...,74,15,4,1670,4,299,1,135,26,1
0,18,0,0,2,1,1,119,35,20,0,...,113,16,8,1930,2,232,2,101,13,1
0,25,0,0,3,3,3,313,41,23,1,...,159,15,7,2112,4,472,6,116,22,1
0,22,1,0,1,0,1,150,40,15,1,...,177,18,5,2088,7,327,1,87,47,1
0,10,1,0,1,0,2,70,33,11,0,...,83,15,2,1486,6,153,2,100,28,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,31,2,2,1,1,0,346,36,25,4,...,141,12,7,2021,0,487,1,20,0,9
0,22,1,0,2,1,0,250,43,24,2,...,117,13,6,1954,1,367,1,63,9,9
0,28,1,0,0,0,0,310,36,23,1,...,123,11,4,1646,2,433,0,30,21,9
0,24,0,0,2,2,0,215,29,21,2,...,125,14,11,2066,4,340,2,20,25,9
0,18,1,0,1,1,1,225,32,21,2,...,72,11,5,1534,5,297,2,52,18,9

In [138]:
y=saved_df["game_won"]
x=saved_df[list(saved_df.columns)[5:len(saved_df)]]

x,xtest,y,ytest= train_test_split(x,y)

clf = LogisticRegression(max_iter=500)
clf.fit(x, y)
#theta = clf.coef_
#mse = mean_squared_error(clf.predict(xtest), ytest)

#print("Optimal theta:", theta)
#print("Cost", mse)

print(ytest)
clf.predict(xtest)

#clf.score(xtest,ytest)

0    0
0    1
0    0
0    0
0    1
    ..
0    0
0    0
0    0
0    1
0    0
Name: game_won, Length: 209, dtype: int64

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0])

In [142]:

test=Boxscore(Boxscores(1,2019).games['1-2019'][3]['boxscore']).dataframe
test_x=test[['away_first_downs', 'away_fourth_down_attempts', 'away_fourth_down_conversions',
       'away_fumbles', 'away_fumbles_lost', 'away_interceptions', 'away_net_pass_yards',
       'away_pass_attempts', 'away_pass_completions', 'away_pass_touchdowns', 'away_pass_yards',
       'away_penalties', 'away_points', 'away_rush_attempts', 'away_rush_touchdowns', 'away_rush_yards',
       'away_third_down_attempts', 'away_third_down_conversions', 'away_time_of_possession',
       'away_times_sacked', 'away_total_yards', 'away_turnovers', 'away_yards_from_penalties',
       'away_yards_lost_from_sacks']]
test_x['week']=[1]

<ipython-input-142-3a8c0cc209ef>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_x['week']=[1]

In [143]:
test_x = game_data_up_to_week(range(10,11),2018)

In [153]:
test_x_new=test_x[list(test_x.columns)[5:len(test_x.columns)]]
test_x["game_won"]

0    0
0    1
0    1
0    0
0    0
0    1
0    1
0    0
0    0
0    1
0    1
0    0
0    0
0    1
0    0
0    1
0    0
0    1
0    1
0    0
0    0
0    1
0    0
0    1
0    1
0    0
0    1
0    0
Name: game_won, dtype: int64

In [151]:
clf.predict(test_x_new)

array([0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1])

In [ ]:
my_list = []
# where i is the iteration in for loop
for i in range(0, len(my_data)):
if i % 2 == 0:
my_list.append("away")
else:
my_list.append("home")
my_data['home_away'] = my_list
my_data

In [97]:
first_team = saved_df[saved_df["team_abbr"] == "atl"]
second_team = saved_df[saved_df["team_abbr"] == "buf"]

In [108]:
first_team['team'] = np.ones(first_team.shape[0])
second_team['team'] = np.zeros(second_team.shape[0])
all_team = pd.concat([first_team,second_team])
all_team[list(all_team.columns)[0:4]+list(all_team.columns)[6:len(list(all_team.columns))]]
x=all_team[]

<ipython-input-108-3a4d25d6e3b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  first_team['team'] = np.ones(first_team.shape[0])
<ipython-input-108-3a4d25d6e3b9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  second_team['team'] = np.zeros(second_team.shape[0])

,team_name,team_abbr,score,game_won,fourth_down_attempts,fourth_down_conversions,fumbles,fumbles_lost,interceptions,net_pass_yards,...,third_down_attempts,third_down_conversions,time_of_possession,times_sacked,total_yards,turnovers,yards_from_penalties,yards_lost_from_sacks,week,team
0,Atlanta Falcons,atl,12,0,1,0,1,0,1,225,...,15,4,1670,4,299,1,135,26,1,1.0
0,Atlanta Falcons,atl,31,1,0,0,3,0,1,272,...,11,6,1782,0,442,1,26,0,2,1.0
0,Atlanta Falcons,atl,37,0,0,0,0,0,0,359,...,11,4,1760,3,407,0,54,15,3,1.0
0,Atlanta Falcons,atl,36,0,1,0,0,0,0,403,...,15,11,1762,3,495,0,95,16,4,1.0
0,Atlanta Falcons,atl,17,0,3,1,1,1,0,262,...,14,6,1852,6,324,1,75,43,5,1.0
0,Atlanta Falcons,atl,34,1,0,0,2,0,0,347,...,13,8,1899,1,417,0,30,8,6,1.0
0,Atlanta Falcons,atl,23,1,0,0,1,1,0,356,...,13,7,1937,3,423,1,29,23,7,1.0
0,Atlanta Falcons,atl,38,1,0,0,0,0,1,337,...,13,10,1976,2,491,1,50,13,9,1.0
0,Buffalo Bills,buf,3,0,1,0,1,0,2,70,...,15,2,1486,6,153,2,100,28,1,0.0
0,Buffalo Bills,buf,20,0,0,0,1,0,2,209,...,14,5,1618,5,293,2,31,36,2,0.0
0,Buffalo Bills,buf,27,1,1,1,3,0,0,164,...,13,4,2145,3,292,0,84,32,3,0.0
0,Buffalo Bills,buf,0,0,0,0,1,1,2,87,...,16,3,1523,7,145,3,20,64,4,0.0
0,Buffalo Bills,buf,13,1,3,2,0,0,1,79,...,13,4,2029,1,223,1,30,3,5,0.0
0,Buffalo Bills,buf,13,0,0,0,2,1,2,129,...,15,6,1980,2,229,3,104,16,6,0.0
0,Buffalo Bills,buf,5,0,1,0,2,2,3,168,...,9,2,1601,2,303,5,59,7,7,0.0
0,Buffalo Bills,buf,6,0,2,0,3,1,1,287,...,14,4,1690,3,333,2,51,26,8,0.0
0,Buffalo Bills,buf,9,0,3,1,1,1,3,166,...,18,6,2043,4,264,4,163,22,9,0.0

In [35]:
def get_schedule(year):
    weeks = list(range(1,18))
    schedule_df = pd.DataFrame()
    for w in range(len(weeks)):
        date_string = str(weeks[w]) + '-' + str(year)
        week_scores = Boxscores(weeks[w],year)
        week_games_df = pd.DataFrame()
        for g in range(len(week_scores.games[date_string])):
            game = pd.DataFrame(week_scores.games[date_string][g], index = [0])[['away_name', 'away_abbr','home_name', 'home_abbr','winning_name', 'winning_abbr' ]]
            game['week'] = weeks[w]
            week_games_df = pd.concat([week_games_df,game])
        schedule_df = pd.concat([schedule_df, week_games_df]).reset_index().drop(columns = 'index') 
    return schedule_df

In [48]:
get_schedule(2018)

,away_name,away_abbr,home_name,home_abbr,winning_name,winning_abbr,week
0,Atlanta Falcons,atl,Philadelphia Eagles,phi,Philadelphia Eagles,phi,1
1,Pittsburgh Steelers,pit,Cleveland Browns,cle,None,None,1
2,Buffalo Bills,buf,Baltimore Ravens,rav,Baltimore Ravens,rav,1
3,Jacksonville Jaguars,jax,New York Giants,nyg,Jacksonville Jaguars,jax,1
4,Houston Texans,htx,New England Patriots,nwe,New England Patriots,nwe,1
...,...,...,...,...,...,...,...
251,San Francisco 49ers,sfo,Los Angeles Rams,ram,Los Angeles Rams,ram,17
252,Cincinnati Bengals,cin,Pittsburgh Steelers,pit,Pittsburgh Steelers,pit,17
253,Chicago Bears,chi,Minnesota Vikings,min,Chicago Bears,chi,17
254,Oakland Raiders,rai,Kansas City Chiefs,kan,Kansas City Chiefs,kan,17
255,Indianapolis Colts,clt,Tennessee Titans,oti,Indianapolis Colts,clt,17

IndexError: list index out of range